---
title: "Data cleaning"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{data_cleaning}
  %\VignettePackage{tidymass}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

## **Data preparation**

We just use the dataset which are from [this step](https://tidymass.github.io/tidymass/articles/explore_data.html).


```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
library(tidymass)
load("data_cleaning/POS/object_pos")
load("data_cleaning/NEG/object_neg")
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
object_pos
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
object_neg
```

## Data quality assessment before data cleaning

Here, we can use the `massqc` pacakge to [assess the data quality](https://tidymass.github.io/massqc/).

We can just use the `massqc_report()` function to get a html format quality assessment report.

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
massqc::massqc_report(object = object_pos, path = "data_cleaning/POS/data_quality")
```

## **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
sessionInfo()
```
