---
title: "Pathway enrichment"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    number_sections: true
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{pathway_enrichment
  %\VignettePackage{tidymass}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Data preparation**

Load the differential expressional metabolites.

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
library(tidymass)
library(tidyverse)
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
load("statiscal_analysis/object")
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
object
```

# **Pathway enrichment**

All the results will be placed in a folder named as `pathway_enrichment`.

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
dir.create(path = "pathway_enrichment", showWarnings = FALSE)
```


```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
diff_metabolites <-
  object %>% 
  activate_mass_dataset(what = "variable_info") %>% 
  filter(p_value_adjust < 0.05) %>% 
  extract_variable_info()
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
head(diff_metabolites)
```


## Load KEGG pathway human database

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
data("kegg_hsa_pathway", package = "metpath")
kegg_hsa_pathway
```
```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
get_pathway_class(kegg_hsa_pathway)
```

Remove the disease pathways:

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
#get the class of pathways
pathway_class = 
  metpath::pathway_class(kegg_hsa_pathway)
head(pathway_class)
```


```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
remain_idx =
  pathway_class %>%
  unlist() %>%
  stringr::str_detect("Disease") %>%
  `!`() %>%
  which()

remain_idx
```


```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
pathway_database =
  kegg_hsa_pathway[remain_idx]
pathway_database
```


```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
kegg_id <-
  diff_metabolites$KEGG.ID 
kegg_id <-
  kegg_id[!is.na(kegg_id)]
kegg_id
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
result = 
enrich_kegg(query_id = kegg_id, 
            query_type = "compound", 
            id_type = "KEGG",
            pathway_database = pathway_database, 
            p_cutoff = 0.05, 
            p_adjust_method = "BH", 
            threads = 3)
```


Check the result:

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
result
```


# **Plot to show pathway enrichment**

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
enrich_bar_plot(object = result,
                x_axis = "p_value",
                cutoff = 0.05)
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
enrich_scatter_plot(object = result, y_axis = "p_value", y_axis_cutoff = 0.05)
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
enrich_network(
  object = result,
  point_size = "p_value",
  p_cutoff = 0.05,
  only_significant_pathway = TRUE
)
```

# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
sessionInfo()
```
