---
title: "Get started"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2022-08-07 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{tidymass}
  %\VignettePackage{tidymass}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Installation**

You can install `tidymass` from [GitLab](https://gitlab.com/tidymass/tidymass)

``` {r,eval=FALSE,warning=FALSE, R.options="", message=FALSE, cache=TRUE, code_folding=TRUE}
if(!require(remotes)){
install.packages("remotes")
}
remotes::install_gitlab("tidymass/tidymass")
```

or [GitHub](https://github.com/tidymass/tidymass)

```{r,eval=FALSE,warning=FALSE, R.options="", message=FALSE, cache=TRUE, code_folding=TRUE}
remotes::install_github("tidymass/tidymass")
```

# **Check versions of all the packages in tidymass**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE, code_folding=TRUE}
tidymass::check_tidymass_version()
```

# **Update packages in tidymass**

```{r,eval=FALSE,warning=FALSE, R.options="", message=FALSE, cache=TRUE, code_folding=TRUE}
tidymass::update_tidymass()
```

# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE, code_folding=TRUE}
sessionInfo()
```